
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author geovanna
 */
public class TelaCadasCliente extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadasCliente
     */
    public TelaCadasCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCPF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCel = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtEnd = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtCEP = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtDN = new javax.swing.JTextField();
        btnCadas = new javax.swing.JButton();
        txtCan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(1, 3, 115));
        jPanel1.setForeground(new java.awt.Color(245, 245, 245));

        jLabel1.setForeground(new java.awt.Color(245, 245, 245));
        jLabel1.setText("Cadastro de Cliente");

        jLabel2.setForeground(new java.awt.Color(245, 245, 245));
        jLabel2.setText("Nome Completo");

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(245, 245, 245));
        jLabel3.setText("CPF");

        jLabel4.setForeground(new java.awt.Color(245, 245, 245));
        jLabel4.setText("Email");

        jLabel5.setForeground(new java.awt.Color(245, 245, 245));
        jLabel5.setText("Celular");

        jLabel6.setForeground(new java.awt.Color(245, 245, 245));
        jLabel6.setText("Endereço para Entrega / Nº");

        jLabel7.setForeground(new java.awt.Color(245, 245, 245));
        jLabel7.setText("CEP");

        jLabel8.setForeground(new java.awt.Color(245, 245, 245));
        jLabel8.setText("Data de Nascimento");

        btnCadas.setText("Cadastrar");
        btnCadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadasActionPerformed(evt);
            }
        });

        txtCan.setText("Cancelar");
        txtCan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(57, 57, 57)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCel, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(41, 41, 41)
                                        .addComponent(jLabel8))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(538, 538, 538)
                                        .addComponent(txtCan, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtDN, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(btnCadas, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(343, 343, 343)
                        .addComponent(jLabel1)))
                .addGap(0, 39, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtCel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(txtCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtDN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCan, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(btnCadas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
       
    }//GEN-LAST:event_txtNomeActionPerformed

    private void btnCadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadasActionPerformed
        if(txtNome.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Campo Nome Vazio", "ERRO", JOptionPane.ERROR_MESSAGE);
        }
        else if(txtCPF.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Campo CPF Vazio", "ERRO", JOptionPane.ERROR_MESSAGE);
        }
        else if(txtEmail.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Campo Email Vazio", "ERRO", JOptionPane.ERROR_MESSAGE);
        }
        else if(txtCel.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Campo Celular Vazio", "ERRO", JOptionPane.ERROR_MESSAGE);
        }
        else if(txtCEP.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Campo CEP Vazio", "ERRO", JOptionPane.ERROR_MESSAGE);
        }
        else if(txtEnd.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Campo Endereço Vazio", "ERRO", JOptionPane.ERROR_MESSAGE);
        }
        else if(txtDN.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Campo Data de Nascimento Vazio", "ERRO", JOptionPane.ERROR_MESSAGE);
        }
        else{
            JOptionPane.showMessageDialog(null,"Cliente Cadastrado Com Sucesso");
        }
        
        
        TelaLogin tl = new TelaLogin();
        TelaCadasCliente tc = new TelaCadasCliente();
        TelaCadasFunc tf = new TelaCadasFunc();
        TelaCadasProd tp = new TelaCadasProd();
        TelaCompra tcmp = new TelaCompra();
        TelaNotaFiscal tn= new TelaNotaFiscal();
        
        int escolha;
        
           
            String esc = JOptionPane.showInputDialog(  "Escolha uma opção: "
                                            + "\n1- Cadastro de Cliente"
                                            + "\n2- Cadastro de Produto"
                                            + "\n3- Cadastro de Funcionário"
                                            + "\n4- Cadastrar Compra"
                                            + "\n5- Cadastrar Nota Fiscal"
                                            + "\n6- Sair");
            escolha = Integer.parseInt(esc);
            
            switch(escolha){
                case 1:
                    tc.setVisible(true);
                    tp.setVisible(false);
                    tf.setVisible(false);
                    tcmp.setVisible(false);
                    tn.setVisible(false);
                    tl.setVisible(false);
                    break;
                case 2:
                    tp.setVisible(true);
                    tc.setVisible(false);
                    tf.setVisible(false);
                    tcmp.setVisible(false);
                    tn.setVisible(false);
                    tl.setVisible(false);
                    break;
                case 3:
                    tf.setVisible(true);
                    tc.setVisible(false);
                    tp.setVisible(false);
                    tcmp.setVisible(false);
                    tn.setVisible(false);
                    tl.setVisible(false);
                    break;
                case 4:
                    tcmp.setVisible(true);
                    tc.setVisible(false);
                    tp.setVisible(false);
                    tf.setVisible(false);
                    tn.setVisible(false);
                    tl.setVisible(false);
                    break;
                case 5:
                    tn.setVisible(true);
                    tc.setVisible(false);
                    tp.setVisible(false);
                    tf.setVisible(false);
                    tcmp.setVisible(false);
                    tl.setVisible(false);
                    break;
                case 6:
                        System.exit(0);
                        break;
                default:
                    JOptionPane.showMessageDialog(null, "Opção Inválida", "ERRO", JOptionPane.ERROR_MESSAGE);
            }
            
           
    }//GEN-LAST:event_btnCadasActionPerformed

    private void txtCanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCanActionPerformed
      TelaLogin tl = new TelaLogin();
        TelaCadasCliente tc = new TelaCadasCliente();
        TelaCadasFunc tf = new TelaCadasFunc();
        TelaCadasProd tp = new TelaCadasProd();
        TelaCompra tcmp = new TelaCompra();
        TelaNotaFiscal tn= new TelaNotaFiscal();
        
        int escolha;
        
           
            String esc = JOptionPane.showInputDialog(  "Escolha uma opção: "
                                            + "\n1- Cadastro de Cliente"
                                            + "\n2- Cadastro de Produto"
                                            + "\n3- Cadastro de Funcionário"
                                            + "\n4- Cadastrar Compra"
                                            + "\n5- Cadastrar Nota Fiscal"
                                            + "\n6- Sair");
            escolha = Integer.parseInt(esc);
            
            switch(escolha){
                case 1:
                    tc.setVisible(true);
                    tp.setVisible(false);
                    tf.setVisible(false);
                    tcmp.setVisible(false);
                    tn.setVisible(false);
                    tl.setVisible(false);
                    break;
                case 2:
                    tp.setVisible(true);
                    tc.setVisible(false);
                    tf.setVisible(false);
                    tcmp.setVisible(false);
                    tn.setVisible(false);
                    tl.setVisible(false);
                    break;
                case 3:
                    tf.setVisible(true);
                    tc.setVisible(false);
                    tp.setVisible(false);
                    tcmp.setVisible(false);
                    tn.setVisible(false);
                    tl.setVisible(false);
                    break;
                case 4:
                    tcmp.setVisible(true);
                    tc.setVisible(false);
                    tp.setVisible(false);
                    tf.setVisible(false);
                    tn.setVisible(false);
                    tl.setVisible(false);
                    break;
                case 5:
                    tn.setVisible(true);
                    tc.setVisible(false);
                    tp.setVisible(false);
                    tf.setVisible(false);
                    tcmp.setVisible(false);
                    tl.setVisible(false);
                    break;
                case 6:
                        System.exit(0);
                        break;
                default:
                    JOptionPane.showMessageDialog(null, "Opção Inválida", "ERRO", JOptionPane.ERROR_MESSAGE);
            }
            
           
    }//GEN-LAST:event_txtCanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadasCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadasCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadasCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadasCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadasCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtCEP;
    private javax.swing.JTextField txtCPF;
    private javax.swing.JButton txtCan;
    private javax.swing.JTextField txtCel;
    private javax.swing.JTextField txtDN;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEnd;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
